name: ROS2 Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Set up ROS 2
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL http://repos.ros.org/repos/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        sudo apt install -y python3-colcon-common-extensions


    - name: Build ROS 2 workspace
      run: |
        mkdir -p ~/ros2_ws/src
        cd ~/ros2_ws/src
        git clone https://github.com/Viimaple/ros2_ws.git
        cd ~/ros2_ws
        colcon build


    - name: Source ROS 2 setup
      run: |
        source /opt/ros/humble/setup.bash
        source ~/ros2_ws/install/setup.bash

    - name: Run ROS2 test
      run: bash -xv ./test.bash
